version: '3'
services:
  odoo:
    image: odoo:16.0
    env_file: .env
    depends_on: [postgres]
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  odoo-data:
  db-data:
